# Generated by Django 4.2 on 2023-06-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id_c', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip_src', models.CharField(max_length=200)),
                ('ip_dst', models.CharField(max_length=200)),
                ('protocole', models.CharField(max_length=200)),
                ('src_port', models.CharField(max_length=200)),
                ('dst_port', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeCapture',
            fields=[
                ('id_dc', models.BigAutoField(primary_key=True, serialize=False)),
                ('interface_reseau', models.CharField(max_length=200)),
                ('Nbr_paquet', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
