# Generated by Django 4.2 on 2023-06-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_capture_demandecapture_delete_choice_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Capture',
        ),
        migrations.DeleteModel(
            name='DemandeCapture',
        ),
    ]
