# Generated by Django 4.2 on 2023-06-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandecapture',
            name='Nbr_paquet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='demandecapture',
            name='interface_reseau',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='demandecapture',
            name='nom_demande',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
