# Generated by Django 4.2 on 2023-08-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_demandecapture_nbr_paquet_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Capture',
        ),
        migrations.DeleteModel(
            name='DemandeCapture',
        ),
    ]
