# Generated by Django 4.2 on 2023-08-20 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_demandecapture_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_u', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=200)),
                ('mdp', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='demandecapture',
            name='id',
        ),
        migrations.AddField(
            model_name='demandecapture',
            name='id_u',
            field=models.ForeignKey(db_column='id_u', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.user'),
        ),
    ]
