# Generated by Django 4.2 on 2023-08-20 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0009_user_remove_demandecapture_id_demandecapture_id_u'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandecapture',
            name='id_u',
        ),
        migrations.AddField(
            model_name='demandecapture',
            name='id',
            field=models.ForeignKey(db_column='id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
