# Generated by Django 4.2 on 2023-08-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_demandecapture_id_u_demandecapture_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandecapture',
            name='Filtre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
