# Generated by Django 4.2 on 2023-08-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_demandecapture_filtre'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecapture',
            name='etat',
            field=models.IntegerField(blank=True, max_length='200', null=True),
        ),
    ]
