# Generated by Django 4.2 on 2023-08-20 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_demandecapture_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandecapture',
            name='etat',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
