# Generated by Django 4.2 on 2023-09-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_demandecapture_etat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capture',
            name='dst_port',
        ),
        migrations.RemoveField(
            model_name='capture',
            name='ip_dst',
        ),
        migrations.RemoveField(
            model_name='capture',
            name='ip_src',
        ),
        migrations.RemoveField(
            model_name='capture',
            name='protocole',
        ),
        migrations.RemoveField(
            model_name='capture',
            name='src_port',
        ),
        migrations.AddField(
            model_name='capture',
            name='capture_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capture',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandecapture',
            name='interface_reseau',
            field=models.CharField(blank=True, choices=[('0', 'lo'), ('1', 'enp0s3'), ('2', 'enp0s8')], max_length=200),
        ),
    ]
